const $=id=>document.getElementById(id);
const KEY="seguros_v2";
const MONTHS=["","Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
let data=JSON.parse(localStorage.getItem(KEY)||"[]").map(x=>({...x,phone:x.phone||"",document:x.document||"",email:x.email||"",insurer:x.insurer||"",branch:x.branch||"",startDate:x.startDate||"",endDate:x.endDate||"",claim:x.claim||"Não",endorsement:x.endorsement||"Não",endorsementValue:Number(x.endorsementValue||0),endorsementType:x.endorsementType||"Pagar",paymentMethod:x.paymentMethod||"À vista",installments:Number(x.installments||1),history:Array.isArray(x.history)?x.history:[]}));
let editReturnState=null;
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const totalPremium=x=>Number(x.value||0)+(x.endorsement==="Sim"?(x.endorsementType==="Restituir"?-1:1)*Number(x.endorsementValue||0):0);
const renewalDate=x=>{const [y,m,d]=String(x.endDate||x.startDate||"").split("-").map(Number);return {y:y||0,m:m||0,d:d||0}};
function nextRenewalDate(x,base=new Date()){const q=renewalDate(x);if(!q.m||!q.d)return null;let year=Number(x.lastRenewalYear)?Number(x.lastRenewalYear)+1:q.y;if(!year)return null;let t=new Date(year,q.m-1,q.d);let r=new Date(base.getFullYear(),base.getMonth(),base.getDate());while(t<r)t.setFullYear(t.getFullYear()+1);return t}
function daysUntil(x,base=new Date()){const t=nextRenewalDate(x,base);if(!t)return null;const r=new Date(base.getFullYear(),base.getMonth(),base.getDate());return Math.round((t-r)/86400000)}
function state(x){if(x.status==="Cancelado")return ["status-cancelado","Cancelado"];const now=new Date(),q=renewalDate(x);if(!q.y||!q.m)return ["status-ativo","Ativo"];const dueYear=Number(x.lastRenewalYear)?Number(x.lastRenewalYear)+1:q.y;return now.getFullYear()===dueYear&&now.getMonth()+1===q.m?["status-renovar","A renovar"]:["status-ativo","Ativo"]}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p)?.classList.remove("hidden");const t={dashboard:["Dashboard","Visão geral da sua operação"],clientes:["Clientes","Ficha e relacionamento com seus clientes"],seguros:["Seguros","Consulte, filtre e gerencie sua carteira"],novo:["Novo seguro","Cadastre os dados do seguro e da vigência"],alertas:["Central de alertas","Renovações que exigem acompanhamento"],relatorios:["Relatórios","Indicadores e distribuição da carteira"],financeiro:["Financeiro","Valores dos seguros e condições de pagamento"]}[p];if(t){$("pageTitle").textContent=t[0];$("pageSubtitle").textContent=t[1]}document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="dashboard")renderDashboard();if(p==="seguros")renderTable();if(p==="clientes")renderClients();if(p==="alertas")renderAlertsPage();if(p==="relatorios")renderReports();if(p==="financeiro")renderFinance()}
function newForm(){$("insuranceForm")?.reset();$("editId").value="";$("manualStatus").value="Ativo";$("installments").value=1;$("formTitle").textContent="Cadastrar seguro"}
$("loginForm").addEventListener("submit",e=>{e.preventDefault();if($("username").value==="pgseguros"&&$("password").value==="PgBc@2027"){$("login").classList.add("hidden");$("app").classList.remove("hidden");showPage("dashboard")}else $("loginError").textContent="Usuário ou senha incorretos."});
$("logout").onclick=()=>{$("app").classList.add("hidden");$("login").classList.remove("hidden");$("password").value=""};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>b.dataset.page==="novo"?(newForm(),showPage("novo")):showPage(b.dataset.page));
$("quickNew")?.addEventListener("click",()=>{newForm();showPage("novo")});
$("cancelEdit")?.addEventListener("click",()=>{newForm();showPage("seguros")});
$("insuranceForm").addEventListener("submit",e=>{e.preventDefault();const id=$("editId").value,old=id?data.find(x=>x.id===id):null;const returnState=id?editReturnState:null;const item={id:id||crypto.randomUUID(),client:$("client").value.trim(),phone:$("phone").value.trim(),document:$("document").value.trim(),email:$("email").value.trim(),insurer:$("insurer").value,branch:$("branch").value,value:Number($("value").value),startDate:$("startDate").value,endDate:$("endDate").value,claim:$("claim").value,endorsement:$("endorsement").value,endorsementValue:Number($("endorsementValue").value||0),endorsementType:$("endorsementType").value,paymentMethod:$("paymentMethod").value,installments:Number($("installments").value||1),status:$("manualStatus").value,note:$("note").value.trim(),lastRenewalYear:id?(old?.lastRenewalYear||null):null,createdAt:old?.createdAt||Date.now(),history:old?.history||[]};if(id)data=data.map(x=>x.id===id?item:x);else data.push(item);save();showPage("seguros");if(returnState){requestAnimationFrame(()=>{requestAnimationFrame(()=>{const row=[...document.querySelectorAll("#tableBody tr[data-insurance-id]")].find(r=>r.dataset.insuranceId===returnState.id);if(row){row.scrollIntoView({block:"center",behavior:"smooth"});row.classList.add("edit-return-highlight");setTimeout(()=>row.classList.remove("edit-return-highlight"),2200)}else window.scrollTo({top:returnState.scrollY||0,behavior:"smooth"});editReturnState=null})})}});
function renderDashboard(){const today=new Date(),active=data.filter(x=>state(x)[1]==="Ativo").length,renewing=data.filter(x=>state(x)[1]==="A renovar").length,next30=data.filter(x=>state(x)[1]!=="Cancelado").filter(x=>{const d=daysUntil(x,today);return d!==null&&d>=0&&d<=30}).length;$("activeCount").textContent=active;$("renewalCount").textContent=renewing;$("next30Count").textContent=next30;const recent=[...data].sort((a,b)=>b.createdAt-a.createdAt).slice(0,5);$("lastClient").textContent=recent[0]?.client?recent[0].client.split(" ")[0]:"—";const up=[...data].filter(x=>state(x)[1]!=="Cancelado").sort((a,b)=>(nextRenewalDate(a,today)?.getTime()||Infinity)-(nextRenewalDate(b,today)?.getTime()||Infinity)).slice(0,6);$("upcomingRenewals").innerHTML=up.length?up.map(x=>{const st=state(x),q=renewalDate(x),days=daysUntil(x,today);return `<div class="renew-item"><span><span class="renew-month">${q.d&&q.m?String(q.d).padStart(2,"0")+"/"+String(q.m).padStart(2,"0"):"—"}</span><br><span class="renew-name">${esc(x.client)}</span><small class="renew-detail">${esc(x.insurer||"—")} · ${esc(x.branch||"—")}${days!==null?` · ${days===0?"renova hoje":days===1?"amanhã":"em "+days+" dias"}`:""}</small></span><span class="status ${st[0]}">${st[1]}</span></div>`}).join(""):"<div class='empty'>Nenhuma renovação cadastrada.</div>";const counts=Array(12).fill(0);data.forEach(x=>{if(state(x)[1]!=="Cancelado"){const m=renewalDate(x).m;if(m)counts[m-1]++}});const max=Math.max(...counts,1),labels=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];$("renewalBars").innerHTML=labels.map((lab,i)=>`<div class="bar-row"><span>${lab}</span><div class="bar-track"><i style="width:${counts[i]?Math.max(counts[i]/max*100,10):0}%"></i></div><b>${counts[i]}</b></div>`).join("");renderAlertsMini();const branches={};data.forEach(x=>{if(state(x)[1]!=="Cancelado")branches[x.branch||"Sem ramo"]=(branches[x.branch||"Sem ramo"]||0)+1});const br=Object.entries(branches).sort((a,b)=>b[1]-a[1]).slice(0,8),bm=Math.max(...br.map(x=>x[1]),1);$("branchBars").innerHTML=br.length?br.map(([n,v])=>`<div class="bar-row"><span class="branch-label">${esc(n)}</span><div class="bar-track"><i style="width:${Math.max(v/bm*100,10)}%"></i></div><b>${v}</b></div>`).join(""):"<div class='empty'>Nenhum seguro cadastrado.</div>";$("recent").innerHTML=recent.map(x=>{const st=state(x);return `<div class="recent-item"><span class="activity-client"><span class="activity-dot ${st[0]}"></span><span><b>${esc(x.client)}</b><br><span class="muted">${esc(x.insurer||"—")} · ${esc(x.branch||"—")}</span></span></span><span><span class="status ${st[0]}">${st[1]}</span><br><b class="activity-value">${money(totalPremium(x))}</b></span></div>`}).join("")||"<div class='empty'>Nenhum seguro cadastrado.</div>"}
function renderAlertsMini(){const today=new Date(),items=data.filter(x=>state(x)[1]!=="Cancelado").map(x=>({x,d:daysUntil(x,today)})).filter(o=>o.d!==null&&o.d<=30).sort((a,b)=>a.d-b.d).slice(0,6);$("renewalAlerts").innerHTML=items.length?items.map(o=>`<div class="alert-item"><span><b>${esc(o.x.client)}</b><small>${o.d===0?"Renova hoje":o.d===1?"Renova amanhã":"Renova em "+o.d+" dias"} · ${esc(o.x.insurer||"—")}</small></span><span class="alert-badge">${o.d<=7?"URGENTE":"PRÓXIMO"}</span></div>`).join(""):"<div class='empty'>Nenhuma renovação nos próximos 30 dias.</div>"}
function renderTable(){const q=$("search").value.toLowerCase(),ins=$("filterInsurer")?.value||"",br=$("filterBranch")?.value||"",rm=$("filterRenewal")?.value||"",fs=$("filterStatus")?.value||"";const rows=data.filter(x=>{const qd=renewalDate(x);return [x.client,x.phone,x.document,x.email,x.insurer,x.branch].join(" ").toLowerCase().includes(q)&&(!ins||x.insurer===ins)&&(!br||x.branch===br)&&(!rm||String(qd.m)===rm)&&(!fs||state(x)[1]===fs)});$("resultCount").textContent=`${rows.length} ${rows.length===1?"registro":"registros"}`;$("empty").classList.toggle("hidden",rows.length>0);$("tableBody").innerHTML=rows.map(x=>{const s=state(x),q=renewalDate(x),renew=s[1]==="A renovar"?`<button class="action renew" onclick="renewItem('${x.id}')">Marcar renovado</button>`:"",cancel=s[1]!=="Cancelado"?`<button class="action cancel" onclick="cancelItem('${x.id}')">Cancelar</button>`:"",date=q.d&&q.m?String(q.d).padStart(2,"0")+"/"+String(q.m).padStart(2,"0")+"/"+(q.y||""):"—";return `<tr data-insurance-id="${esc(x.id)}"><td><b>${esc(x.client)}</b></td><td>${esc(x.phone||"—")}</td><td>${esc(x.insurer||"—")}</td><td>${esc(x.branch||"—")}</td><td><b>${money(totalPremium(x))}</b></td><td>${date}</td><td><span class="status ${s[0]}">${s[1]}</span>${x.claim==="Sim"?'<span class="tag">Sinistro</span>':""}${x.endorsement==="Sim"?'<span class="tag">Endosso</span>':""}</td><td><button class="action view" onclick="viewItem('${x.id}')">Ver</button><button class="action edit" onclick="editItem('${x.id}')">Editar</button><button class="action whatsapp" onclick="whatsappItem('${x.id}')">WhatsApp</button>${renew}${cancel}<button class="action print" onclick="printItem('${x.id}')">Imprimir</button><button class="action delete" onclick="deleteItem('${x.id}')">Excluir</button></td></tr>`}).join("")}
["search","filterInsurer","filterBranch","filterRenewal","filterStatus"].forEach(id=>$(id)?.addEventListener("input",renderTable));
function clientGroups(){const map={};data.forEach(x=>{const k=(x.document||x.client||"").trim().toLowerCase();if(!map[k])map[k]={key:k,client:x.client,phone:x.phone,document:x.document,email:x.email,items:[]};map[k].items.push(x)});return Object.values(map)}
function renderClients(){const q=$("clientSearch")?.value.toLowerCase()||"";const groups=clientGroups().filter(g=>[g.client,g.phone,g.document,g.email].join(" ").toLowerCase().includes(q));$("clientCount").textContent=`${groups.length} ${groups.length===1?"cliente":"clientes"}`;$("clientsGrid").innerHTML=groups.length?groups.map(g=>{const active=g.items.filter(x=>state(x)[1]==="Ativo").length,alerts=g.items.filter(x=>state(x)[1]==="A renovar").length;return `<div class="client-card"><div class="client-top"><div class="client-avatar">${esc((g.client||"?").slice(0,1).toUpperCase())}</div><div><h3>${esc(g.client)}</h3><p>${esc(g.phone||"Sem telefone")} · ${esc(g.email||"Sem e-mail")}</p></div></div><div class="client-stats"><span><b>${g.items.length}</b> seguro(s)</span><span><b>${active}</b> ativo(s)</span><span class="${alerts?'attention':''}"><b>${alerts}</b> a renovar</span></div><div class="client-actions"><button class="action view" onclick="viewClient('${encodeURIComponent(g.key)}')">Abrir ficha</button>${g.phone?`<button class="action whatsapp" onclick="whatsappNumber('${esc(g.phone)}')">WhatsApp</button>`:""}</div></div>`}).join(""):"<div class='empty'>Nenhum cliente encontrado.</div>"}
$("clientSearch")?.addEventListener("input",renderClients);
function renderAlertsPage(){const today=new Date();const buckets=[{title:"Renovam hoje",filter:d=>d===0,cls:"danger"},{title:"Próximos 7 dias",filter:d=>d>0&&d<=7,cls:"warning"},{title:"Este mês",filter:d=>{const t=nextRenewalDate({endDate:""});return false},cls:"info"}];const arr=data.filter(x=>state(x)[1]!=="Cancelado").map(x=>({x,d:daysUntil(x,today)})).filter(o=>o.d!==null&&o.d<=31).sort((a,b)=>a.d-b.d);$("alertsPage").innerHTML=buckets.slice(0,2).map(b=>{const rows=arr.filter(o=>b.filter(o.d));return `<div class="alert-section"><div class="alert-section-head"><h3>${b.title}</h3><span>${rows.length}</span></div>${rows.length?rows.map(o=>`<div class="alert-large"><div><b>${esc(o.x.client)}</b><small>${esc(o.x.insurer||"—")} · ${esc(o.x.branch||"—")} · ${o.d===0?"Hoje":"em "+o.d+" dias"}</small></div><div><button class="action view" onclick="viewItem('${o.x.id}')">Ver</button><button class="action whatsapp" onclick="whatsappItem('${o.x.id}')">WhatsApp</button></div></div>`).join(""):"<div class='empty'>Nenhum seguro nesta faixa.</div>"}</div>`}).join("")+`<div class="alert-section"><div class="alert-section-head"><h3>Renovações do mês</h3><span>${data.filter(x=>state(x)[1]==="A renovar").length}</span></div>${data.filter(x=>state(x)[1]==="A renovar").map(x=>`<div class="alert-large"><div><b>${esc(x.client)}</b><small>${esc(x.insurer||"—")} · ${esc(x.branch||"—")}</small></div><button class="action renew" onclick="renewItem('${x.id}')">Marcar renovado</button></div>`).join("")||"<div class='empty'>Nenhum seguro a renovar neste mês.</div>"}</div>`}
function renderReports(){const active=data.filter(x=>state(x)[1]!=="Cancelado").length,ren=data.filter(x=>state(x)[1]==="A renovar").length,total=data.reduce((s,x)=>s+totalPremium(x),0);$("reportKpis").innerHTML=`<div class="report-kpi"><span>Clientes</span><b>${clientGroups().length}</b></div><div class="report-kpi"><span>Seguros ativos</span><b>${active}</b></div><div class="report-kpi"><span>A renovar</span><b>${ren}</b></div><div class="report-kpi"><span>Valor total dos seguros</span><b>${money(total)}</b></div>`;const make=(field)=>{const o={};data.forEach(x=>{if(state(x)[1]!=="Cancelado")o[x[field]||"Não informado"]=(o[x[field]||"Não informado"]||0)+1});return Object.entries(o).sort((a,b)=>b[1]-a[1])};$("reportInsurers").innerHTML=make("insurer").map(([n,v])=>`<div class="report-row"><span>${esc(n)}</span><b>${v}</b></div>`).join("")||"<div class='empty'>Sem dados.</div>";$("reportBranches").innerHTML=make("branch").map(([n,v])=>`<div class="report-row"><span>${esc(n)}</span><b>${v}</b></div>`).join("")||"<div class='empty'>Sem dados.</div>"}
function renderFinance(){const total=data.reduce((s,x)=>s+totalPremium(x),0),base=data.reduce((s,x)=>s+Number(x.value||0),0),endorse=data.reduce((s,x)=>s+(x.endorsement==="Sim"?(x.endorsementType==="Restituir"?-1:1)*Number(x.endorsementValue||0):0),0);$("financeKpis").innerHTML=`<div class="report-kpi"><span>Valor dos seguros</span><b>${money(base)}</b></div><div class="report-kpi"><span>Endossos</span><b>${money(endorse)}</b></div><div class="report-kpi"><span>Valor total</span><b>${money(total)}</b></div>`;$("financeBody").innerHTML=data.map(x=>`<tr><td><b>${esc(x.client)}</b></td><td>${money(x.value)}</td><td>${x.endorsement==="Sim"?money((x.endorsementType==="Restituir"?-1:1)*x.endorsementValue):"—"}</td><td><b>${money(totalPremium(x))}</b></td><td>${esc(x.paymentMethod||"—")}</td><td>${Number(x.installments||1)}x</td></tr>`).join("")||`<tr><td colspan="6">Nenhum seguro cadastrado.</td></tr>`}
window.editItem=id=>{const x=data.find(v=>v.id===id);if(!x)return;editReturnState={id:x.id,scrollY:window.scrollY,filters:{search:$("search")?.value||"",filterInsurer:$("filterInsurer")?.value||"",filterBranch:$("filterBranch")?.value||"",filterRenewal:$("filterRenewal")?.value||"",filterStatus:$("filterStatus")?.value||""}};$("editId").value=x.id;["client","phone","document","email","insurer","branch","value","startDate","endDate","claim","endorsement","endorsementValue","endorsementType","paymentMethod","installments","note"].forEach(k=>$(k).value=x[k]??"");$("manualStatus").value=x.status==="Cancelado"?"Cancelado":"Ativo";$("formTitle").textContent="Editar seguro";showPage("novo");window.scrollTo({top:0,behavior:"smooth"})};
window.renewItem=id=>{const x=data.find(v=>v.id===id);if(x){const q=renewalDate(x);x.history=x.history||[];x.history.push({type:"Renovação",date:new Date().toISOString().slice(0,10),from:x.endDate,to:q.y?`${q.y+1}-${String(q.m).padStart(2,"0")}-${String(q.d).padStart(2,"0")}`:"",value:x.value});x.lastRenewalYear=new Date().getFullYear();x.status="Ativo";save()}};
window.cancelItem=id=>{const x=data.find(v=>v.id===id);if(x&&confirm("Marcar este seguro como cancelado?")){x.status="Cancelado";x.history=x.history||[];x.history.push({type:"Cancelamento",date:new Date().toISOString().slice(0,10)});save()}};
window.deleteItem=id=>{if(confirm("Excluir este seguro?")){data=data.filter(x=>x.id!==id);save();showPage("seguros")}};
window.whatsappNumber=phone=>{let n=String(phone).replace(/\D/g,"");if(!n)return;if(n.length===10||n.length===11)n="55"+n;window.open(`https://wa.me/${n}?text=${encodeURIComponent("Olá! Estou entrando em contato sobre o seu seguro.")}`,"_blank")};
window.whatsappItem=id=>{const x=data.find(v=>v.id===id);if(x?.phone)whatsappNumber(x.phone);else alert("Este cliente não possui telefone cadastrado.")};
window.viewClient=encoded=>{const g=clientGroups().find(v=>v.key===decodeURIComponent(encoded));if(!g)return;openDetail(g.client,g.items,g)};
window.viewItem=id=>{const x=data.find(v=>v.id===id);if(x)openDetail(x.client,[x],null)};
function openDetail(name,items,client){const old=$("detailModal");if(old)old.remove();const html=`<div id="detailModal" class="modal-backdrop" onclick="if(event.target===this)this.remove()"><div class="modal-card"><button class="modal-close" onclick="document.getElementById('detailModal').remove()">×</button><div class="modal-title"><div class="client-avatar">${esc((name||"?").slice(0,1).toUpperCase())}</div><div><h2>${esc(name)}</h2><p>${esc(client?.phone||items[0]?.phone||"Sem telefone")} · ${esc(client?.email||items[0]?.email||"Sem e-mail")}</p></div></div><div class="detail-list">${items.map(x=>{const s=state(x),q=renewalDate(x);return `<div class="detail-card"><div class="detail-card-head"><b>${esc(x.branch||"Seguro")}</b><span class="status ${s[0]}">${s[1]}</span></div><div class="detail-grid"><span><small>Seguradora</small><b>${esc(x.insurer||"—")}</b></span><span><small>Valor do seguro</small><b>${money(x.value)}</b></span><span><small>Valor total</small><b>${money(totalPremium(x))}</b></span><span><small>Vigência</small><b>${esc(x.startDate||"—")} → ${esc(x.endDate||"—")}</b></span><span><small>Pagamento</small><b>${esc(x.paymentMethod||"—")} · ${x.installments||1}x</b></span><span><small>Sinistro / Endosso</small><b>${esc(x.claim||"Não")} / ${esc(x.endorsement||"Não")}</b></span></div><div class="detail-actions"><button class="action edit" onclick="document.getElementById('detailModal').remove();editItem('${x.id}')">Editar</button>${x.phone?`<button class="action whatsapp" onclick="whatsappItem('${x.id}')">WhatsApp</button>`:""}<button class="action print" onclick="printItem('${x.id}')">Imprimir</button></div>${x.history?.length?`<div class="history"><b>Histórico</b>${x.history.slice(-5).reverse().map(h=>`<div><span>${esc(h.type)}</span><small>${esc(h.date||"")} ${h.to?"→ "+esc(h.to):""}</small></div>`).join("")}</div>`:""}</div>`}).join("")}</div></div></div>`;document.body.insertAdjacentHTML("beforeend",html)}
window.printItem=id=>{const x=data.find(v=>v.id===id);if(!x)return;const s=state(x)[1],html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Ficha - ${esc(x.client)}</title><style>body{font-family:Arial;color:#172033;padding:40px;max-width:800px;margin:auto}h1{color:#174f96}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{padding:12px;border:1px solid #e2e8f0;border-radius:8px}.label{font-size:10px;color:#667085;text-transform:uppercase;font-weight:bold}.value{margin-top:4px;font-size:14px}</style></head><body><h1>PG Seguros</h1><p>Ficha do seguro</p><div class="grid"><div class="box"><div class="label">Cliente</div><div class="value">${esc(x.client)}</div></div><div class="box"><div class="label">Telefone</div><div class="value">${esc(x.phone||"—")}</div></div><div class="box"><div class="label">Seguradora</div><div class="value">${esc(x.insurer||"—")}</div></div><div class="box"><div class="label">Ramo</div><div class="value">${esc(x.branch||"—")}</div></div><div class="box"><div class="label">Valor do seguro</div><div class="value">${money(x.value)}</div></div><div class="box"><div class="label">Valor total</div><div class="value">${money(totalPremium(x))}</div></div><div class="box"><div class="label">Status</div><div class="value">${esc(s)}</div></div><div class="box"><div class="label">Vigência</div><div class="value">${esc(x.startDate||"—")} → ${esc(x.endDate||"—")}</div></div></div><p>Pagamento: ${esc(x.paymentMethod||"—")} · ${x.installments||1} parcela(s)</p><p>Sinistro: ${esc(x.claim||"Não")} · Endosso: ${esc(x.endorsement||"Não")}</p>${x.note?`<p>Observações: ${esc(x.note)}</p>`:""}<script>window.onload=()=>window.print()<\/script></body></html>`;const w=window.open("","_blank");w.document.write(html);w.document.close()};
function exportBackup(){const payload={app:"PG Seguros",version:"7.0",exportedAt:new Date().toISOString(),data};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`pg-seguros-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("exportBackup")?.addEventListener("click",exportBackup);$("importBackupBtn")?.addEventListener("click",()=>$("importBackup").click());$("importBackup")?.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result),incoming=Array.isArray(p)?p:p.data;if(!Array.isArray(incoming))throw 0;if(confirm(`Restaurar ${incoming.length} seguros? Os dados atuais serão substituídos.`)){data=incoming.map(x=>({...x,id:x.id||crypto.randomUUID(),history:Array.isArray(x.history)?x.history:[]}));save();showPage("seguros");alert("Backup restaurado com sucesso.")}}catch(_){alert("Não foi possível restaurar este backup.")}e.target.value=""};r.readAsText(f)});
$("printReport")?.addEventListener("click",()=>window.print());
function renderAll(){renderDashboard();renderTable();if(!$('clientes').classList.contains('hidden'))renderClients();if(!$('alertas').classList.contains('hidden'))renderAlertsPage();if(!$('relatorios').classList.contains('hidden'))renderReports();if(!$('financeiro').classList.contains('hidden'))renderFinance()}
renderAll();
